import 'controller/launch_controller.dart';import 'package:alli_s_application7/core/app_export.dart';import 'package:alli_s_application7/widgets/custom_button.dart';import 'package:flutter/material.dart';class LaunchScreen extends GetWidget<LaunchController> {const LaunchScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.pinkA100, body: Container(width: double.maxFinite, padding: getPadding(left: 15, right: 15), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Spacer(), Padding(padding: getPadding(left: 60, right: 60), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [SizedBox(height: getVerticalSize(138), width: getHorizontalSize(104), child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgLayer2, height: getVerticalSize(126), width: getHorizontalSize(104), alignment: Alignment.topCenter), Align(alignment: Alignment.bottomRight, child: Text("lbl_uladluch".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtOpenSansItalicLight17))])), Padding(padding: getPadding(top: 5), child: Text("lbl_sleep_sounds".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtOpenSansRomanBold34))])), CustomImageView(svgPath: ImageConstant.imgPaginator, height: getVerticalSize(43), width: getHorizontalSize(311), margin: getMargin(top: 41)), CustomButton(height: getVerticalSize(50), text: "lbl_next".tr, margin: getMargin(left: 34, top: 24), variant: ButtonVariant.FillBluegray90001, fontStyle: ButtonFontStyle.OpenSansItalicLight17, onTap: () {onTapNext();}, alignment: Alignment.centerRight)])))); } 
/// Navigates to the loginSlideTwoScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the loginSlideTwoScreen.
onTapNext() { Get.toNamed(AppRoutes.loginSlideTwoScreen, ); } 
 }
