import 'controller/viewroutine_feeding_bottle_tab_container_controller.dart';import 'package:alli_s_application7/core/app_export.dart';import 'package:alli_s_application7/presentation/viewroutine_feeding_bottle_page/viewroutine_feeding_bottle_page.dart';import 'package:alli_s_application7/presentation/viewroutine_feeding_solids_page/viewroutine_feeding_solids_page.dart';import 'package:alli_s_application7/presentation/viewroutine_page/viewroutine_page.dart';import 'package:alli_s_application7/widgets/app_bar/appbar_image.dart';import 'package:alli_s_application7/widgets/app_bar/appbar_subtitle.dart';import 'package:alli_s_application7/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class ViewroutineFeedingBottleTabContainerScreen extends GetWidget<ViewroutineFeedingBottleTabContainerController> {const ViewroutineFeedingBottleTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.gray100, appBar: CustomAppBar(height: getVerticalSize(92), leadingWidth: 80, leading: AppbarImage(height: getSize(48), width: getSize(48), svgPath: ImageConstant.imgMdiarrowleft, margin: getMargin(left: 32, top: 3, bottom: 4), onTap: () {onTapMdiarrowleft1();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_feeding_f".tr), actions: [AppbarImage(height: getSize(40), width: getSize(40), svgPath: ImageConstant.imgEdit, margin: getMargin(left: 32, top: 7, right: 32, bottom: 8))]), body: SizedBox(width: size.width, child: SingleChildScrollView(padding: getPadding(top: 10), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [SizedBox(height: getVerticalSize(64), width: getHorizontalSize(336), child: TabBar(controller: controller.tabviewController, labelColor: ColorConstant.black900, labelStyle: TextStyle(fontSize: getFontSize(24), fontFamily: 'Open Sans', fontWeight: FontWeight.w300), unselectedLabelColor: ColorConstant.black900, unselectedLabelStyle: TextStyle(fontSize: getFontSize(24), fontFamily: 'Open Sans', fontWeight: FontWeight.w300), indicatorPadding: getPadding(all: 0.5), indicator: BoxDecoration(color: ColorConstant.pinkA100, borderRadius: BorderRadius.circular(getHorizontalSize(8))), tabs: [Tab(child: Text("lbl_breast".tr, overflow: TextOverflow.ellipsis)), Tab(child: Text("lbl_bottle".tr, overflow: TextOverflow.ellipsis)), Tab(child: Text("lbl_solids".tr, overflow: TextOverflow.ellipsis))])), SizedBox(height: getVerticalSize(788), child: TabBarView(controller: controller.tabviewController, children: [ViewroutinePage(), ViewroutineFeedingBottlePage(), ViewroutineFeedingSolidsPage()]))]))))); } 
/// Navigates to the homeScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the homeScreen.
onTapMdiarrowleft1() { Get.toNamed(AppRoutes.homeScreen, ); } 
 }
