import 'controller/onboarding_two_controller.dart';import 'package:alli_s_application7/core/app_export.dart';import 'package:alli_s_application7/widgets/app_bar/appbar_image.dart';import 'package:alli_s_application7/widgets/app_bar/custom_app_bar.dart';import 'package:alli_s_application7/widgets/custom_button.dart';import 'package:flutter/material.dart';class OnboardingTwoScreen extends GetWidget<OnboardingTwoController> {const OnboardingTwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(116), title: Container(width: getHorizontalSize(132), margin: getMargin(left: 29, top: 41), child: Text("lbl_welcome_to_pbm".tr, maxLines: null, textAlign: TextAlign.left, style: AppStyle.txtNunitoBold30PinkA100)), actions: [AppbarImage(height: getVerticalSize(98), width: getHorizontalSize(168), imagePath: ImageConstant.imgVector5, margin: getMargin(bottom: 18))]), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.end, children: [Container(height: getSize(8), width: getSize(8), margin: getMargin(top: 60, right: 73), decoration: BoxDecoration(color: ColorConstant.pinkA100, borderRadius: BorderRadius.circular(getHorizontalSize(4)))), Container(height: getSize(8), width: getSize(8), margin: getMargin(top: 34, right: 73), decoration: BoxDecoration(color: ColorConstant.pinkA100, borderRadius: BorderRadius.circular(getHorizontalSize(4)))), Container(height: getSize(8), width: getSize(8), margin: getMargin(top: 25, right: 91), decoration: BoxDecoration(color: ColorConstant.pinkA100, borderRadius: BorderRadius.circular(getHorizontalSize(4)))), CustomButton(height: getVerticalSize(59), width: getHorizontalSize(165), text: "lbl_get_started".tr, margin: getMargin(top: 12), shape: ButtonShape.RoundedBorder29, padding: ButtonPadding.PaddingAll19, fontStyle: ButtonFontStyle.NunitoBold18, onTap: () {onTapGetstarted();}, alignment: Alignment.center), Spacer(), CustomImageView(svgPath: ImageConstant.imgUndrawdoctorshwty, height: getVerticalSize(169), width: getHorizontalSize(227), alignment: Alignment.centerLeft, margin: getMargin(left: 57)), CustomImageView(imagePath: ImageConstant.imgVector3PinkA100, height: getVerticalSize(115), width: getHorizontalSize(375), margin: getMargin(top: 82))])))); } 
/// Navigates to the alreadySignedUpOneScreen when the action is triggered.

/// When the action is triggered, this function uses the `Get` package to
/// push the named route for the alreadySignedUpOneScreen.
onTapGetstarted() { Get.toNamed(AppRoutes.alreadySignedUpOneScreen, ); } 
 }
